Integrated Toms suggestions

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -8,46 +8,46 @@
 # Run xmlformat for XML files being commited
 
 # Extend the variable to search for more config files:
-CONFIG_FILES="~/.config/daps/docbook-xmlformat.conf /etc/daps/docbook-xmlformat.conf"
+XML_FORMAT_CFGS="~/.config/daps/docbook-xmlformat.conf /etc/daps/docbook-xmlformat.conf"
 # The found config file:
-CONFIG=""
-for cfg in $CONFIG_FILES; do
-  if [ -r "$cfg" ]; then
-     CONFIG="$cfg"
-     break
-  fi
+XML_FORMAT_CFG=""
+for cfg in $XML_FORMAT_CFGS; do
+    if [ -r "$cfg" ]; then
+        XML_FORMAT_CFG="$cfg"
+        break
+    fi
 done
 
-if [ -z "$CONFIG" ]; then
+if [ -z "$XML_FORMAT_CFG" ]; then
     echo "ERROR: File 'docbook-xmlformat.conf' not found" >/dev/stderr
     exit 10
 fi
 
-XML_FORMAT_EXECS="/usr/bin/xmlformat //usr/bin/xmlformat.rb usr/bin/xmlformat.pl"
+XML_FORMAT_EXECS="/usr/bin/xmlformat /usr/bin/xmlformat.rb /usr/bin/xmlformat.pl"
 XML_FORMAT=""
 for script in $XML_FORMAT_EXECS; do
-   if [ -x "$script" ]; then
-       XML_FORMAT="$script"
-       break
-   fi
+    if [ -x "$script" ]; then
+        XML_FORMAT="$script"
+        break
+    fi
 done
 
 if [ -z "$XML_FORMAT" ]; then
     echo "ERROR: 'xmlformat' command not found" >/dev/stderr
-￼    exit 10
+    ￼    exit 10
 fi
 
 # get list of 'A'dded and 'M'odified XML files
 XML_FILES=$(git status --porcelain xml/*.xml | awk 'match($1, "M|A") {print $2}' | tr '\n' ' ')
 
 # run xmlformat on ech of them
-for FILE in $XML_FILES; do
-    echo "XML-formatting file: $FILE"
-    XML_FORMAT_OUTPUT="$($XML_FORMAT -i -f $XML_FORMAT_CFG $FILE 2>&1)"
+for file in $XML_FILES; do
+    echo "XML-formatting file: $file"
+    XML_FORMAT_OUTPUT="$($XML_FORMAT -i -f $XML_FORMAT_CFG $file 2>&1)"
     if [ -n $XML_FORMAT_OUTPUT ]; then
         echo "XML format successful"
     else
-        echo "ERROR: Syntax error in file $FILE" >/dev/stderr
+        echo "ERROR: Syntax error in file $file" >/dev/stderr
         exit 10
     fi
 done
